### ISSUE TITLE
Multiple rg.exe and Console Window Host processes after branch checkout

### ISSUE THREAD

**Issue by jazelly** [soates/Auto-Import#127]
Version:          Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS Version:       Windows_NT x64 10.0.19044
CPUs:             Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)
Memory (System):  15.94GB (4.44GB free)

After checking out tags in a large repo, say `node/node.js`, this happened due to large file system update:
![crashing](https://user-images.githubusercontent.com/28685065/229271058-4b901d18-54da-4ef3-aec2-d167dd77face.PNG)

`code --status`
[crash-status2.txt](https://github.com/soates/Auto-Import/files/11128678/crash-status2.txt)

I can confirm this is not an issue with VSCode, as with a clean run, i.e. no extension, it works fine. I had only this extension enabled.

Currently I have to disable this extension while working on repos like this.

**Comment by jazelly** [comment]
Afrer some digging,

**Comment by theranbrig** [comment]
I saw this issue on MacOS as well.  After running bisect it was determined that this one was causing the issue.

**Comment by matthieusieben** [comment]
Still happening today.

In a (very) large project, containing lots of `ts` files, whenever the entire project is re-built, there are so many `rg` processes being spawned that they end-up causing `EMFILE` error (ulimit reached).

The following is an extract of my "Extension Host" output that contains thousands more lines like this one:
```
2024-02-16 15:04:50.619 [error] Error: spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EMFILE
    at P (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1884:5882)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1892:4355
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1892:2925
2024-02-16 15:04:50.620 [error] Error: spawn /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EMFILE
    at P (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1884:5882)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1892:4355
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1892:2925
```

**Comment by altano** [comment]
I am hitting this and also ended up here by diagnosing the problem using VSCode's extension bisect.

I can reliably trigger the issue with `pnpm i --force`

**Comment by kachkaev** [comment]
Same problem on macOS when Auto Import extension is installed. I shared some details here: https://github.com/cursor/cursor/issues/2765#issuecomment-3027186147

**Comment by aspiers** [comment]
Same on Linux today.
