### ISSUE TITLE
Files cannot be saved after the window has been open / in use for a while

### ISSUE THREAD

**Issue by eppsilon** [soates/Auto-Import#24]
I've run into a weird issue where the editor stops saving files when I use the keyboard shortcut or the UI (after clicking the close button on an unsaved file). The UI continues to show the files as unsaved. Restarting VS Code or uninstalling this extension fixes the problem.

I'll try to narrow down the actions/time required to trigger this issue - I know this is all a bit vague.

Original issue from VS Code project: https://github.com/Microsoft/vscode/issues/13492

**Comment by soates** [comment]
Hey, that sucks man - really sorry about that.

Ill start trying to recreate it now but if you have anymore information - let me know!

sorry again :)

**Comment by davityle** [comment]
threadService.ts:222 [Extension Host] Uncaught Exception:  TypeError: Cannot read property 'match' of undefined(anonymous function) @ threadService.ts:222
threadService.ts:222 [Extension Host] TypeError: Cannot read property 'match' of undefined
    at ReadFileContext.callback (/home/tylerdavis/.vscode/extensions/steoates.autoimport-1.2.2/out/src/node-upload.js:42:43)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)(anonymous function) @ threadService.ts:222
threadService.ts:222 [Extension Host] Uncaught Exception:  TypeError: Cannot read property 'match' of undefined(anonymous function) @ threadService.ts:222

**Comment by davityle** [comment]
It's a really bad bug because you loose all of your changes

**Comment by davityle** [comment]
Here is another stack trace 

    shell.ts:441 Cannot read property 'match' of undefined: TypeError: Cannot read property 'match' of undefined
    at ReadFileContext.callback (/home/tylerdavis/.vscode/extensions/steoates.autoimport-1.2.2/out/src/node-upload.js:42:43)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)e.onUnexpectedError @ shell.ts:441(anonymous function) @ shell.ts:354e.onUnexpectedError @ errors.ts:68o @ errors.ts:83t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by soates** [comment]
Thanks guys, I am going to see what I can do with the stack traces.
